[tool.poetry]
name = "email_worker"
version = "1.1.2"
description = "Dockerized - for async email sending, using RabbitMQ, Celery, and Redis"
authors = ["Gabriel de Fombelle <gabriel.de.fombelle@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "worker" }]

[tool.poetry.dependencies]
python = "^3.12"
celery = "^5.0.5"
kombu = "^5.2.0"
pika = "^1.2.1"
aiosmtplib = "^1.1.7"
python-multipart = "^0.0.5"

# Dépendances internes (par défaut pour le dev local)
pytune_helpers = { path = "../../packages/pytune_helpers" }
pytune_configuration = { path = "../../packages/pytune_configuration" }

[tool.poetry.group.docker.dependencies]
# Les mêmes dépendances, mais en version Git (SSH) pour Docker
pytune_helpers = { git = "ssh://git@github.com/gdefombelle/pytune_helpers.git" }
pytune_configuration = { git = "ssh://git@github.com/gdefombelle/pytune_configuration.git" }

[tool.poetry.dev-dependencies]
pytest = "^7.2.2"
black = "^23.0.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
email-worker = "worker.email_worker:main"
